### PR TITLE
Add iNat photos to Taxon objects

### PR DESCRIPTION
**Pull request by kueda**
* Add a script to populate a CSV of CC-licensed iNat taxon photos for taxa this project handles
* eslint config for the version of eslint this project depends on
* Taxa loads iNat taxon photos from inattaxonphotos.csv if present in the data dir

I tried to abide the conventions in this project, with the possible exception of not wrapping the photos in a new Photo class, which I can do if desired. I still need to test this with a project that uses this library, hence the draft.

### CODE REVIEW

**Comment by johnkenny54** [comment]
A few comments on what's here so far.

- I've been working on cleaning up the code, still a work in progress but I believe TypeScript is working in the main branch - currently `npx tsc` shows errors with the code in this branch, so would be good to fix that.
- There are probably inconsistencies in indentation in the existing files - not sure whether most are 2 or 4, but we should probably decide on a standard going forward.
- eslint currently shows a lot of errors - I don't think it's set up yet on the main branch, and I don't have strong opinions on what the standards are, but would be good to set this up so it's not too painful to get rid of the errors eventually (it looks like most of the issues are with indentation)

As for the code itself, it seems to work fine with https://github.com/ca-plants/ebplants.

For the script, is there an easy way to restrict photos to those in California? Is there an easy way to restrict to only research grade observations, and do you think it would make much difference in photo quality?

**Comment by kueda** [comment]
Do you mind if I set up a git pre-commit hook to run `npx eslint` and `npx tsc`? I wasn't even aware you were using typescript (mostly b/c I've never seen [tsdoc](https://tsdoc.org/) comments before, I've only used the default type annotations).

**Comment by kueda** [comment]
> For the script, is there an easy way to restrict photos to those in California? Is there an easy way to restrict to only research grade observations, and do you think it would make much difference in photo quality?

Sorry, forgot to reply to this part. Here I'm using the Taxon Photos, which are directly associated with a Taxon. They might come from iNat observations, but they might also come from else where (Wikimedia, EOL, Flickr), so they can't be filtered by RG status. They are, in general, more diagnostic and more appealing than the average observation photo of any given taxon, so I suspect they will be more appropriate in the context of this project.

That said, we could certainly populate this file with observation photos if you want. I could make a different script that takes obs query options so a user could say, "I want the top-5 most-faves photos of each taxon in Alameda and Contra Costa Counties".

**Comment by johnkenny54** [comment]
I'm fine with you setting up commit hooks.

As for the photos, probably best to leave it as you have it for now. Just having the photos is a big improvement. I can imagine scenarios where it would be desirable to have them curated in various ways, but I don't see an easy way to do this, so let's leave it as something to mull over for the future.

**Comment by johnkenny54** [comment]
I just looked at your last changes and realized you changed to .ts files - I don't think this will work, the code is all JavaScript, the TypeScript checking comes from JSDoc (not TSDoc). There are some .d.ts files with type definitions that I've added manually that can be used by other code (e.g., rusplants) that is using ca-plant-list (they're also used in some of the JSDoc where the type reference is needed but you don't need to import).

Not sure how your development environment is set up, but with mine (VS Code), the editor yells at me if it finds a type error, so I get immediate feedback from the editor as well as npx tsc.

**Comment by kueda** [comment]
Ok, I'll revert to JS. I started writing new files in TS b/c it was much easier to type inline functions correctly without having to rely on type inference and I was assuming you were headed toward typescript if you were using `tsc` to check types.

FWIW, `npx tsc` shows no errors for me in this branch, and while I usually use Sublime, I just checked all the files I touched in VS Code and the only file with errors I see is lib/web/pagetaxon.js, and they're all pre-existing indentation issues. We probably have VS Code configured differently, but it's weird that we get different results from `npx tsc` since we should be running the same version. Maybe a node version issue? I'm using v18.16.0.

**Comment by johnkenny54** [comment]
This all seems fine now. I suspect the type checks worked on the version with the .ts files, I didn't try it on that version, only the previous version.

I've only recently started trying to impose some order on this code, and I'm basing it on what I've seen in other projects. There may be better ways to do some of these things. I haven't seen very many that use TypeScript source, seems like it's a hassle to have to deal with the preprocessing.

Other things I'm planning on doing are adding eslint (which will be partially done once this PR is merged) and Prettier (which I found annoying when it was first imposed on me but I've gotten used to it).

**Pull request merged**
